spring.datasource.url=${DB_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:watermoniter}}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:${PGUSER:postgres}}
spring.datasource.password=${DB_PASSWORD:${PGPASSWORD:postgres}}

spring.h2.console.enabled=false

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
